#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

use Straube\Command\CommandMapper;

$application = new Application('AcmeDemo', '0.1');

$mapper = new CommandMapper(__DIR__.'/../src/', 'Acme\\Demo\\Command');
$mapper->registerCommands($application);

$application->run();
